// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hytbwhakvfbtczefakjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dGJ3aGFrdmZidGN6ZWZha2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTU3NzIsImV4cCI6MjA3MTYzMTc3Mn0.sPNOzlfO5N06Q0k14cCLD4-ophawlJuh92HyvGbEByU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});